TARGET = writer

CC = $(CROSS_COMPILE)gcc

CFLAGS = -Wall -Wextra -g

LDFLAGS = 

SRC = writer.c

OBJ = $(SRC:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(TARGET) $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(TARGET)

